version: '2'
services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=postgres
    image: postgres:9.5
    ports:
      - "5432:5432"
  web:
    environment:
      - PGPASSWORD=postgres
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"

