# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fa96ea941a8bd1d0061eb0f5c60b1eb5207487d2aff615a90021bd2a28e952736deb067c225de87a88eda691412df0adfab3de164de4e87df46ab9df43e4395
  twilio_sid: 'AC726ae221508039568c29c87e6ec3c132'
  twilio_token: 'a14c894848d9d63388aa8429306edd36'
  twilio_number: '+16066574709'

test:
  secret_key_base: 34b9d6ddca23e91b5876449d60f27717858129395a55a13b8cb1b395bfcd6c8189afc2e05aa46ee905bff9e314f7fdef2595f0b58bf447e923e5bcf3aa6da15a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_sid: 'AC726ae221508039568c29c87e6ec3c132'
  twilio_token: 'a14c894848d9d63388aa8429306edd36'
  twilio_number: '+16066574709'
