# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fa96ea941a8bd1d0061eb0f5c60b1eb5207487d2aff615a90021bd2a28e952736deb067c225de87a88eda691412df0adfab3de164de4e87df46ab9df43e4395
  twilio_sid: 'ACb855470124eb62055fa09330ee0212ee'
  twilio_token: '05027ae156ccaeb3126cd90c02dd2d3b'
  twilio_number: '+15005550006'

test:
  secret_key_base: 34b9d6ddca23e91b5876449d60f27717858129395a55a13b8cb1b395bfcd6c8189afc2e05aa46ee905bff9e314f7fdef2595f0b58bf447e923e5bcf3aa6da15a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>
